# Config relating to the Lazygit UI
gui:
  # Config relating to colors and styles.
  # See https://github.com/folke/tokyonight.nvim/blob/main/extras/lazygit/tokyonight_moon.yml
  theme:
    # Border color of focused window
    activeBorderColor:
      - "#ff966c"
      - bold

    # Border color of non-focused windows
    inactiveBorderColor:
      - "#589ed7"

    # Border color of focused window when searching in that window
    searchingActiveBorderColor:
      - "#ff966c"
      - bold

    # Color of keybindings help text in the bottom line
    optionsTextColor:
      - "#82aaff"

    # Background color of selected line.
    # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#highlighting-the-selected-line
    selectedLineBgColor:
      - "#2d3f76"

    # Background color of selected line when view doesn't have focus.
    inactiveViewSelectedLineBgColor:
      - bold

    # Foreground color of copied commit
    cherryPickedCommitFgColor:
      - "#82aaff"

    # Background color of copied commit
    cherryPickedCommitBgColor:
      - "#c099ff"

    # Foreground color of marked base commit (for rebase)
    markedBaseCommitFgColor:
      - "#82aaff"

    # Background color of marked base commit (for rebase)
    markedBaseCommitBgColor:
      - "#ffc777"

    # Color for file with unstaged changes
    unstagedChangesColor:
      - "#c53b53"

    # Default text color
    defaultFgColor:
      - "#c8d3f5"

  # Nerd fonts version to use.
  # One of: '2' | '3' | empty string (default)
  # If empty, do not show icons.
  nerdFontsVersion: "3"
