# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Starship Prompt
# Framed Classic Style
# format = """
# [╭─](blue)$fill[](blue)[ $cmd_duration$time${custom.time_mood}](fg:black bg:blue)$line_break\
# [│ ](blue)$all$line_break\
# [╰─](blue)$fill$line_break\
# $line_break\
# $character
# """

# Framed Minimal Style
# format = """
# [╭─](blue)$fill[](blue)[ $cmd_duration$time${custom.time_mood}](fg:black bg:blue)$line_break\
# [│ ](blue)$all$line_break\
# [╰─ ](blue)$character
# """

# Streamlined Modern Style
format = """
$fill[](blue)[ $cmd_duration$time${custom.time_mood}](fg:black bg:blue)$line_break\
$all$line_break\
$line_break\
$character
"""

# Inserts a blank line between shell prompts
add_newline = true

# Allow a timeout (in milliseconds) of up to 1000 for commands executed by the starship
command_timeout = 1000

[cmd_duration]
format = ' $duration  '

[fill]
symbol = '─'
style = 'blue'

[time]
disabled = false
format = ' $time  '

[custom.time_mood]
disabled = false
command = '''
TIME=$(date +%H)
if [[ "$TIME" -le 17 && "$TIME" -ge 8 ]];then
    time_symbol="󰖙"
elif [[ "$TIME" -le 21 && "$TIME" -ge 18 ]];then
    time_symbol="󰖛"
elif [[ "$TIME" -le 4 || "$TIME" -ge 22 ]];then
    time_symbol="󰖔"
else
    time_symbol="󰖜"
fi
echo "$time_symbol"
'''
format = '$output '
when = true
