# Starship Prompt
format = """
[╭─](blue)$fill[](blue)[ $cmd_duration$time${custom.time_mood}](fg:black bg:blue)$line_break\
[│ ](blue)$all$line_break\
[╰─ ](blue)$character"""

[cmd_duration]
format = ' $duration  '

[fill]
symbol = '─'
style = 'blue'

[time]
disabled = false
format = ' $time  '

[custom.time_mood]
disabled = false
command = '''
TIME=$(date +%H)
if [[ "$TIME" -le 17 && "$TIME" -ge 8 ]];then
    time_symbol="󰖙"
elif [[ "$TIME" -le 21 && "$TIME" -ge 18 ]];then
    time_symbol="󰖛"
elif [[ "$TIME" -le 4 || "$TIME" -ge 22 ]];then
    time_symbol="󰖔"
else
    time_symbol="󰖜"
fi
echo "$time_symbol"
'''
format = '$output '
when = true
