# Starship Prompt
format = '$all$fill$cmd_duration$time$line_break$character'

[cmd_duration]
format = '祥[$duration]($style)'

[fill]
symbol = ' '

[git_branch]
symbol = ' '

[time]
format = 'at [$time]($style) '
disabled = true
