import = [
    "~/.config/alacritty/themes/nord.toml"
]

[window]
dimensions = { columns = 104, lines = 31 }
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.8
blur = true

[font]
normal = { family = "MonaspiceNe Nerd Font Mono", style = "Regular" }
size = 16.0

